### ISSUE TITLE
Failed to install 'wonderpush-cordova-sdk': Error: pod: Command failed with exit code 31

### ISSUE THREAD

**Issue by mitjafelicijan** [wonderpush/wonderpush-cordova-sdk#6]
I am having difficulties getting wonderpush cordova sdk to work. The strangest thing is that this was working for me a month ago.

```sh
$ cordova plugin add wonderpush-cordova-sdk --variable CLIENT_ID=xxxx --variable CLIENT_SECRET=xxxx

Installing "wonderpush-cordova-sdk" for ios
Running command: pod install --verbose
Failed to install 'wonderpush-cordova-sdk': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/m/demo/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Socket.<anonymous> (internal/child_process.js:438:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:672:12)
pod: Command failed with exit code 31
```

I am running this on Catalina with xcode and cocopods etc installed and working.

![Screenshot 2020-12-19 at 20 17 22](https://user-images.githubusercontent.com/296714/102697599-400a8d80-4237-11eb-8dc8-a08598594ae1.png)

**Comment by tavo20** [comment]
Same problem
